name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    permissions:          # ← 追加
      id-token: write
      contents: read
    uses: ./.github/workflows/_terraform.yml
    with:
      environment: dev
      command: apply
    secrets: inherit