name: Terraform Plan

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "terraform/**"

jobs:
  plan:
    permissions:          # ← 追加：OIDC 権限は呼び出し側で付与
      id-token: write
      contents: read
    uses: ./.github/workflows/_terraform.yml
    with:
      environment: dev
      command: plan
    secrets: inherit